"""add_version_fields_for_realtime_sync

Revision ID: f6d037f842c0
Revises: d4e5f6a7b8c9
Create Date: 2025-12-10 23:04:37.585852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6d037f842c0'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add with server_default for existing rows, then we can remove default if needed
    op.add_column('presentations', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('slides', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slides', 'version')
    op.drop_column('presentations', 'version')
    # ### end Alembic commands ###
